apiVersion: v2
name: quine
description: Helm chart for Quine

version: 0.1.0
maintainers:
- name: Josh Cody
  email: josh@thatdot.com
keywords:
- streaming graph
home: https://quine.io

dependencies:
- name: cassandra
  version: 9.1.16
  repository: https://charts.bitnami.com/bitnami

