# Default values for Quine.
name: quine

replicaCount: 1

image:
  repository: thatdot/quine
  pullPolicy: IfNotPresent
  tag: "latest"
  
service:
  name: quine
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080

