# Default values for Quine.
name: quine

replicaCount: 1

image:
  repository: 709825985650.dkr.ecr.us-east-1.amazonaws.com/thatdot/quine-oss:1.1.2
  pullPolicy: IfNotPresent
  tag: "latest"
  
service:
  name: quine
  type: ClusterIP
  externalPort: 8080
  internalPort: 8080

