apiVersion: v1
kind: ConfigMap
metadata:
  name: quine-config
data:
  quine.conf: | 
    {
      "quine": {
        "decline-sleep-when-access-within": "0",
        "decline-sleep-when-write-within": "100ms",
        "dump-config": false,
        "edge-iteration": "reverse-insertion",
        "id": {
          "partitioned": false,
          "type": "uuid"
        },
        "in-memory-hard-node-limit": 75000,
        "in-memory-soft-node-limit": 10000,
        "labels-property": "__LABEL",
        "metrics-reporters": [
          {
            "type": "jmx"
          }
        ],
        "persistence": {
          "journal-enabled": true,
          "snapshot-schedule": "on-node-sleep",
          "snapshot-singleton": false,
          "standing-query-schedule": "on-node-sleep"
        },
        "shard-count": 4,
        "should-resume-ingest": false,
        "store": {
          type = "cassandra",
          endpoints.0 = "quine-cassandra:9042",
          should-create-keyspace = true,
          should-create-tables = true,
          replication-factor=1
        },
        # "store": {
        #   "create-parent-dir": false,
        #   "filepath": "quine.db",
        #   "sync-all-writes": false,
        #   "type": "rocks-db",
        #   "write-ahead-log": true
        # },
        "timeout": "2m",
        "webserver": {
          "address": "0.0.0.0",
          "port": 8080
        }
      }
    }